modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "badmeteoroid"
version = "${version}"
displayName = "BadMeteoroid"
authors = "Yajat Kaul"
description = '''

'''
#logoFile = ""

[[dependencies.badmeteoroid]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.badmeteoroid]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "badmeteoroid.mixins.json"
